# -*- coding: utf-8 -*-
"""vaegan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z51KHpvbylC8FVdm9ysqLkr_CLM3ozWe

# VAEGAN

### Builds VAEGAN
"""

import os
os.environ["KERAS_BACKEND"] = "tensorflow"
!pip install -q git+https://github.com/tensorflow/docs

import tensorflow as tf
import numpy as np
import keras
from keras import ops, layers
import matplotlib.pyplot as plt

# ---------------- Parameters ----------------
batch_size = 64
latent_dim = 2  # small for visualization
discriminator_in_channels = 1
alpha = 0.8    # pixel-space reconstruction weight
beta_max = 0.25 # max KL weight

# ---------------- Load MNIST ----------------
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
all_digits = np.concatenate([x_train, x_test]).astype("float32") / 255.0
all_digits = np.reshape(all_digits, (-1, 28, 28, 1))
all_labels = keras.utils.to_categorical(np.concatenate([y_train, y_test]), 10)

dataset = tf.data.Dataset.from_tensor_slices((all_digits, all_labels))
dataset = dataset.shuffle(buffer_size=1094).batch(batch_size)

# ---------------- Sampling Layer ----------------
class Sampling(layers.Layer):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.seed_generator = keras.random.SeedGenerator(7)
    def call(self, inputs):
        z_mean, z_log_var = inputs
        batch = ops.shape(z_mean)[0]
        dim = ops.shape(z_mean)[1]
        epsilon = keras.random.normal(shape=(batch, dim), seed=self.seed_generator)
        return z_mean + ops.exp(0.5 * z_log_var) * epsilon

# ---------------- Encoder ----------------
encoder_inputs = keras.Input(shape=(28, 28, 1))
x = layers.Conv2D(32, 3, activation="relu", strides=2, padding="same")(encoder_inputs)
x = layers.Conv2D(64, 3, activation="relu", strides=2, padding="same")(x)
x = layers.Flatten()(x)
x = layers.Dense(16, activation="relu")(x)
z_mean = layers.Dense(latent_dim, name="z_mean")(x)
z_log_var = layers.Dense(latent_dim, name="z_log_var")(x)
z = Sampling()([z_mean, z_log_var])
encoder = keras.Model(encoder_inputs, [z_mean, z_log_var, z], name="encoder")

# ---------------- Decoder ----------------
latent_inputs = keras.Input(shape=(latent_dim,))
x = layers.Dense(7 * 7 * 64, activation="relu")(latent_inputs)
x = layers.Reshape((7, 7, 64))(x)
x = layers.Conv2DTranspose(64, 3, activation="relu", strides=2, padding="same")(x)
x = layers.Conv2DTranspose(32, 3, activation="relu", strides=2, padding="same")(x)
decoder_outputs = layers.Conv2DTranspose(1, 3, activation="sigmoid", padding="same")(x)
decoder = keras.Model(latent_inputs, decoder_outputs, name="decoder")

# ---------------- Discriminator ----------------
disc_input = keras.Input(shape=(28, 28, 1))
x = layers.Conv2D(64, (3,3), strides=2, padding="same")(disc_input)
x = layers.LeakyReLU(0.2)(x)
x = layers.Conv2D(128, (3,3), strides=2, padding="same")(x)
x = layers.LeakyReLU(0.2)(x)
features = layers.GlobalMaxPooling2D()(x)
disc_output = layers.Dense(1)(features)
discriminator = keras.Model(disc_input, disc_output, name="discriminator")

# Feature extractor
feature_extractor = keras.Model(discriminator.input, features)

# Freeze feature extractor ONLY
feature_extractor.trainable = False

# ---------------- Build all models to fix tf.Variable issue ----------------
dummy_input = tf.zeros((1, 28, 28, 1))
_ = encoder(dummy_input)
_ = decoder(tf.zeros((1, latent_dim)))
_ = discriminator(dummy_input)
_ = feature_extractor(dummy_input)

# ---------------- VAEGAN Class ----------------
class VAEGAN(keras.Model):
    def __init__(self, encoder, decoder, discriminator, feature_extractor, latent_dim, **kwargs):
        super().__init__(**kwargs)
        self.encoder = encoder
        self.decoder = decoder
        self.discriminator = discriminator
        self.feature_extractor = feature_extractor
        self.latent_dim = latent_dim

        self.total_loss_tracker = keras.metrics.Mean(name="total_loss")
        self.reconstruction_loss_tracker = keras.metrics.Mean(name="reconstruction_loss")
        self.kl_loss_tracker = keras.metrics.Mean(name="kl_loss")
        self.disc_loss_tracker = keras.metrics.Mean(name="discriminator_loss")
        self.epoch_counter = 0

    @property
    def metrics(self):
        return [self.total_loss_tracker, self.reconstruction_loss_tracker,
                self.kl_loss_tracker, self.disc_loss_tracker]

    def compile(self, vae_optimizer, d_optimizer, loss_fn):
        super().compile()
        self.vae_optimizer = vae_optimizer
        self.d_optimizer = d_optimizer
        self.loss_fn = loss_fn

    def train_step(self, data):
        images, labels = data
        self.epoch_counter += 1
        beta = beta_max * min(1.0, self.epoch_counter / 10.0)

        # ---------------- VAE ----------------
        with tf.GradientTape() as tape_vae:
            z_mean, z_log_var, z = self.encoder(images)
            x_tilde = self.decoder(z)

            # ---------------- Pixel reconstruction ----------------
            pixel_loss = tf.reduce_mean(
            tf.reduce_sum(tf.abs(images - x_tilde), axis=[1, 2, 3]) #can change abs to square for more blurry but smoother latent space better abs for digits
            )

        # ---------------- Feature reconstruction ----------------
            real_feat = tf.stop_gradient(self.feature_extractor(images))
            fake_feat = self.feature_extractor(x_tilde)
            feature_loss = tf.reduce_mean(
             tf.reduce_sum(tf.square(real_feat - fake_feat), axis=1)
            )

        # Hybrid loss
            reconstruction_loss = pixel_loss + 0.1 * feature_loss
            kl_loss = -0.5 * tf.reduce_mean(tf.reduce_sum(1 + z_log_var - tf.square(z_mean) - tf.exp(z_log_var), axis=1))
            vae_loss = alpha * reconstruction_loss + beta * kl_loss

        grads = tape_vae.gradient(vae_loss, self.encoder.trainable_weights + self.decoder.trainable_weights)
        self.vae_optimizer.apply_gradients(zip(grads, self.encoder.trainable_weights + self.decoder.trainable_weights))

        # ---------------- Discriminator ----------------
        with tf.GradientTape() as tape_disc:
            real_output = self.discriminator(images)
            real_labels = tf.ones_like(real_output)
            fake_output_vae = self.discriminator(x_tilde)
            fake_labels_vae = tf.zeros_like(fake_output_vae)
            z_random = tf.random.normal(shape=(tf.shape(images)[0], self.latent_dim))
            x_hat = self.decoder(z_random)
            fake_output_gan = self.discriminator(x_hat)
            fake_labels_gan = tf.zeros_like(fake_output_gan)
            d_loss = (self.loss_fn(real_labels, real_output) +
                      self.loss_fn(fake_labels_vae, fake_output_vae) +
                      self.loss_fn(fake_labels_gan, fake_output_gan))

        grads = tape_disc.gradient(d_loss, self.discriminator.trainable_weights)
        self.d_optimizer.apply_gradients(zip(grads, self.discriminator.trainable_weights))

        # ---------------- Metrics ----------------
        self.total_loss_tracker.update_state(vae_loss)
        self.reconstruction_loss_tracker.update_state(reconstruction_loss)
        self.kl_loss_tracker.update_state(kl_loss)
        self.disc_loss_tracker.update_state(d_loss)

        return {"total_loss": self.total_loss_tracker.result(),
                "reconstruction_loss": self.reconstruction_loss_tracker.result(),
                "kl_loss": self.kl_loss_tracker.result(),
                "discriminator_loss": self.disc_loss_tracker.result()}

# ---------------- Train ----------------
vaegan = VAEGAN(encoder, decoder, discriminator, feature_extractor, latent_dim)
vaegan.compile(
    vae_optimizer=keras.optimizers.Adam(learning_rate=1e-3),
    d_optimizer=keras.optimizers.Adam(learning_rate=1e-3),
    loss_fn=keras.losses.BinaryCrossentropy(from_logits=True)
)

vaegan.fit(dataset, epochs=30)

"""### Displays Latent Space"""

import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

def plot_latent_space_images(vaegan, n=7, figsize=10, latent_dim=2):
    # Use PCA to reduce latent_dim to 2D for visualization
    digit_size = 28
    scale = 0.75
    figure = np.zeros((digit_size * n, digit_size * n))

    # Create grid in 2D PCA space
    grid_x = np.linspace(-scale, scale, n)
    grid_y = np.linspace(-scale, scale, n)[::-1]

    for i, yi in enumerate(grid_y):
        for j, xi in enumerate(grid_x):
            # Construct a latent vector
            z_sample = np.zeros((1, latent_dim))
            z_sample[0, 0:2] = [xi, yi]  # assign first 2 dims
            x_decoded = vaegan.decoder.predict(z_sample, verbose=0)
            digit = x_decoded[0].reshape(digit_size, digit_size)
            figure[
                i * digit_size : (i + 1) * digit_size,
                j * digit_size : (j + 1) * digit_size,
            ] = digit

    plt.figure(figsize=(figsize, figsize))
    start_range = digit_size // 2
    end_range = n * digit_size + start_range
    pixel_range = np.arange(start_range, end_range, digit_size)
    sample_range_x = np.round(grid_x, 1)
    sample_range_y = np.round(grid_y, 1)
    plt.xticks(pixel_range, sample_range_x)
    plt.yticks(pixel_range, sample_range_y)
    plt.imshow(figure, cmap="Greys_r")
    plt.show()

plot_latent_space_images(vaegan)